import mysql.connector as sql
conn=sql.connect(host='localhost',user='root',passwd='',database='database')
if conn.is_connected():
      print('successfully connected')
c1=conn.cursor()

c1.execute('create table hospitals(srno int, name varchar(25), location varchar(25), area varchar(25))')
c1.execute('insert into hospitals values(1, Manipal Hospital, HAL Old Airport Rd, Marathahalli)')
c1.execute('insert into hospitals values(2, Sakra Hospital, Outer Ring Rd, Marathahalli)')
c1.execute('insert into hospitals values(3, Columbia Asia, Varthur Kodi, Whitefield)')
c1.execute('insert into hospitals values(4, Narayana Hrudhalaya, Hosur Rd, Electronic City)')
c1.execute('insert into hospitals values(5, Blossom Hospital, Central Jail Rd, Electronic City)')
c1.execute('insert into hospitals values(6, Fortis Clinic, Bannerghatta Rd, Electronic City)')
c1.execute('insert into hospitals values(7, Apollo Hospital, 14th Cross Rd, Jayanagar)')
c1.execute('insert into hospitals values(8, Aster CMI, New Airport Rd, Hebbal)')
c1.execute('insert into hospitals values(9, Sparsh Hospital, Infantry Rd, Jayanagar)')
c1.execute('insert into hospitals values(10, BGS Gleneagles Hospital, Richmond Rd, Jaynagar)')
c1.execute('insert into hospitals values(11, Sagar Hospital, Banashankari, Jayanagar)')
c1.execute('insert into hospitals values(12, Ramaiah Memorial Hospital, BEL Rd, Hebbal)')
c1.execute('insert into hospitals values(13, Bangalore Baptist Hospital, Vinayakanagar, Hebbal)')
c1.execute('insert into hospitals values(14, Kauvery Hospital, Hewlett Packard Av, Electronic City)')
c1.execute('insert into hospitals values(15, Mallya Hospital, Cubbon Park, Jayanagar)')

c1.execute('create table manipal(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table sakra(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table columbia(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table narayana(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table blossom(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table fortis(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table apollo(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table aster(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table sparsh(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table bgs(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table sagar(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table ramaiah(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table blrbaptist(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table kauvery(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')
c1.execute('create table mallya(Contact_No char(15), No_beds_available int, Cost_of_bed int, Oxygen_available char(3), ambulance int, covid_test_cost int, vaccines_available varchar(30), CT_scan_price int, MRI_scan_price int, XRAY_price int, general_consultation_price int)')

c1.execute("insert into manipal values('1800-102-5555', 300, 8000, 'Yes', 2000, 1200, 'Covaxin, Covidshield', 7000, 10000, 1200, 1000)")

